### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by minad** [acowley/hpp#3]
Hi Anthony,

at first, thanks for the library!

I am trying to use it to do simple preprocessing, but without the capability to read files. This is something I can easily do using the free monad apporach, you have chosen. However I still find your library hard to use and I wonder how stable the internals are (I've seen you had a different architecture before)?

Maybe you could consider movin to the "more standard" packages for free monads, mtl, parsec/megaparsec/attoparsec etc. instead of implementing them in the hpp package yourself? I think this would make things simpler and improve the integration with other stuff. What do you think about using only a free monad for everything instead of using a mixed approach with mtl-like capabilities and free monads? Alternatively everything could be provided by a mtl capability class.

Daniel

**Comment by acowley** [comment]
Hi, @minad! The internal churn is due to bending over backwards to avoid dependencies as there is a plan that this package will be pulled into GHC to avoid depending on an external `cpp`. That said, I'm sorry it's been a nuisance for you.

For use as a library, my intention was that `hppFileContents` would be pretty much the only entry point, but since you are fighting the free monad / mtl mishmash, it seems that you need lower level access. If you let me know what you need, I'll better understand where the internals are leaking.

As for refactoring, I'm all for it! The free monad part is just for the IO done during preprocessing, amounting to proper navigation of the include search path and basic file reading. The MTL-ish part came in particularly when I was wrestling with string representations -- and the streaming thereof -- given that `text` was off limits due to the need to avoid dependencies. So much for history, I'd be happy with an approach that just used mtl capability classes as you say and got rid of the free monad stuff.

The test runner is pretty good at backstopping refactorings (I should know), so feel free to move things around. One thing that is not automated yet is benchmarking, so one has to check on some test cases as one goes. 

On that note, if you are willing to help out, a sample C program as in the test suite is a very distinct test case from a large Haskell file (I was pointed to `Parser.hs` in GHC's source as a measuring stick since it's quite long), so we should test both. The C programs, while short, follow a remarkably convoluted path through system include files, while the Haskell file is really just racing through the lines of that file. During development, I regularly ran against both to see how performance was going. I apologize for that not being a better story!

**Comment by minad** [comment]
Thx for your quick reply. I suspected that you want to have it in ghc for which the small number of dependencies makes sense. Just one question - what about bytestring-trie vs unordered-containers vs containers. They are not allowed in ghc, but bytestring-trie is?

My main point is that using the library directly (for example embedding it in my own free monad or embedding it in my own mtl stack just for string processing) seemed inconvenient and tedious due to the mixed mtl and free monad approach taken. As you said it probably would be the best to remove the free monad stuff and handle all state/error/io stuff using mtl-style classes - which should also have a favorable performance according to what I've heard recently. Maybe I will give it a try!

**Comment by minad** [comment]
It seems I don't get the test suite running on debian stable x86_64 after about half an hour of fiddling...

**Comment by acowley** [comment]
Yes, `bytestring-trie` is a dangling loose end at this point: I need to see if performance in token lookup is a bottleneck or not in typical use cases. I used `bytestring-trie` as a stopgap to avoid that possibility since I was working on the streaming side of things.

I didn't even consider that someone would want to use `hpp` by embedding it into their own monad! Well, that's why feedback is important 😛 I'll take another look at the code with that use in mind.

Regarding the test suite, it does run on travis-ci, did you take a look at how that's set up?

**Comment by minad** [comment]
Yeah I am using the travis variant, but basically nothing works  :stuck_out_tongue:

1. sf download didn't work -> used different mirror
2. it tried at first the cabal variant -> but travis/stack version works on my setup
3. now i get compilation errors (main not defined and stuff...)

Seems to be a bit fragile unfortunately...

**Comment by minad** [comment]
these are not big problems, it is just that they cost precious time which I could hack something reasonable instead ;)

**Comment by acowley** [comment]
I changed the `curl` command that does the SourceForge download, and it works on travis; not sure why the same scripting doesn't work for you. Sorry the project isn't reasonable enough for you, but I appreciate the feedback on use as part of a transformer stack!

**Comment by minad** [comment]
With reasonable I meant doing Haskell instead of debugging shell scripts or this mcpp test runner ;)

I tried a bit harder and it seems that hpp only produces #line as output and nothing else. Then I get a compilation error obviously. I haven't found out yet why.
