### ISSUE TITLE
The library is poorly documented and hard to use

### ISSUE THREAD

**Issue by treeowl** [acowley/hpp#4]
The `hpp` library was written to support the `hpp` executable, and unfortunately it really shows. There is virtually no documentation on using the library, and it seems somewhat poorly organized and limited.

**Comment by acowley** [comment]
This is a singularly unhelpful bug report. If you are an OSS troll, please take this act elsewhere as I’m your entire audience here.

**Comment by treeowl** [comment]
I'm not an OSS troll. Just someone who was looking to figure out how to use
the library and largely failing. I'm sorry I wasn't more specific; I can
try to go into more detail.

**Comment by acowley** [comment]
The entire public API is the half dozen definitions exported by the Hpp module. If what is there is not expressive enough, then we can clean up more. If it’s not clear how to use what is there, then let me know if you think it’s more that the documentation on those things isn’t enough, or that examples would be most helpful... or both!

**Comment by acowley** [comment]
I'm going to close this issue as you do seem to genuinely be interested in helping, and I think there are plenty of concrete problems with the way `hpp` is put together.

I do suggest asking for help with using a library you can't figure out before opening Issues with vague condemnations. Just saying that you want to do X, but don't know where to begin would have been a heck of a lot nicer to see here.

**Comment by treeowl** [comment]
Knowing that `Hpp` is supposed to be the whole public interface definitely helps me focus my comments more. Under that assumption, I note the following shortcomings. I'm not sure how you want to deal with them now that you've closed the ticket.

### `Config` and `Env`

The `hppIO` and `hppFileContents` functions are almost self-explanatory, except that it's not clear what `Config` or `Env` mean or how one is supposed to produce values of those types. It seems almost certain that the `Env` type is not supposed to be built by hand, but there are no functions in `Hpp` for producing it. It appears that `Config` values are supposed to be produced either by hand or from `ConfigF Maybe` values, but `Hpp` does not export `Config`, `ConfigF (Config)`, or `realizeConfig`.

Some users might also find it helpful to have a note somewhere explaining that `hppIO` is a sort of continuation-passing version of `hppFileContents` with different error handling.

### `HppT`

`Hpp` doesn't export `HppT` or `HppF (..)`. Even if it did, it would not be obvious what to *do* with them. `WriteOutput` seems fairly straightforward, but what's the difference between `ReadFile` and `ReadNext`, and what are the `Int` values they contain? I suspect you *might* be better off using an off-the-shelf stream type like the one from `streaming` (see also `streaming-bytestring`) since that will give users a library of nice things to do, but in any case the base functor needs more documentation if it's supposed to be used directly. If it's *not* intended to be used directly, then `Hpp` should probably include some functions for *consuming* `HppT` values once they're produced.

### `Parser`?

`preprocess` produces `HppT [String] (Parser m [TOKEN]) ()`, but `Hpp` doesn't say what a `Parser` is or how one is supposed to use one. It also doesn't export the `TOKEN` synonym or the underlying `Token` type.

### Mystery constraints

`HppCaps` is defined as `(HasError t, HasHppState t, HasEnv t)`, but `Hpp` doesn't export any of those three classes.

**Comment by treeowl** [comment]
Another thing: I only just realized that the lists of strings passed to some functions seem to be lines to process before processing anything else. It would be really helpful to document this explicitly. Additionally, `hppReadFile` takes an `Int` argument with no explanation.

**Comment by acowley** [comment]
These are awesome notes, thank you!

**Comment by acowley** [comment]
I had assumed users would be regular Haskell users since this is such a niche package (i.e. anticipated audience is a Haskell library author who wants to use CPP, but not depend on a C compiler). It's conventional for packages to expose a primary API through a top-level module, while secondary things are in nested modules which can be browsed by clicking through the type signatures in the haddocks, but this seems to have caused a lot of confusion here, so I apologize for not spelling that out in the `README` which was never adequately updated since the time when the package only provided the executable.

The `README` clearly needs an example of using the package as a library.  I'll write a standalone example that takes the argument parsing out of the `Hpp.CmdLine` module and add that to the `README`.

The internal confusion of concepts involving `Parser` and such is due to originally wanting to avoid all dependencies for eventual inclusion in GHC since its reliance on C compilers has historically been an unfortunate source of breakage. The plan was to inline minimal implementations of whatever is needed by `hpp` in `hpp`, but not expose any of it to avoid anyone thinking to rely on `hpp` for streaming or general parsing. I'm not interested in pursuing the GHC angle any more, but exposing less of the implementation should be a straightforward improvement achieved by exporting a composition of `runHpp` and `dischargeHppCaps` that makes `preprocess` more immediately usable. 

The resulting API should be something like, `preprocess :: [String] -> Hpp`, `emptyHppState :: HppState`,  `runHpp :: MonadIO m => HppState -> Hpp -> ExcepT Error m ([String], HppState)`, and `streamHpp :: MonadIO m => HppState -> ([String] -> IO ()) -> Hpp -> ExceptT Error m HppState`. (Hopefully not an `IO ()` for the output stream.) I'll reorganize things to look more like that, and better hide the `ReadFile` and `ReadNext` pieces since they're really only relevant to folks who already know about CPP and need low level access for some reason.

**Comment by treeowl** [comment]
I'm aware of the usual way packages are structured. Typically, though, there would be "public" modules corresponding to each of the major components (types), as well as "internal" modules implementing the guts. It's up to you whether you want to follow that model or keep the whole public interface in one module, but I do think there should be a sufficiently complete public API that it becomes clear to users what each piece does and how they fit together. May I ask why you abandoned the GHC integration idea? It seems to have some good motivation behind it.

**Comment by acowley** [comment]
Okay, I see this is a @well-typed bug report. Look, another program whose usability as a library is [notoriously bad](https://twitter.com/ndm_haskell/status/517410595822649344) is GHC. Now imagine the rant your colleague @thoughtpolice would post on Reddit if somebody opened a GHC bug whose entirety was,

> The `ghc` library was written to support the `ghc` executable, and unfortunately it really shows. There is virtually no documentation on using the library, and it seems somewhat poorly organized and limited.

Obviously true; entirely unhelpful and discouraging. That you do not think others are deserving of the same respect is a great example of why I steer clear of GHC development. I had talked to @bgamari about him helping integrate `hpp` in GHC when I first wrote `hpp`, but his attention has been better spent elsewhere and the time passed. 

The [branch](https://github.com/acowley/hpp/tree/files-read) I created for the other issue you opened should now address the problems you had with starting at the `Hpp` module to find an entry point to the library, and I will update the `README` with the little unit test I added to exercise basic functionality. Despite how rocky this was, at least the package should be more usable.

**Comment by treeowl** [comment]
I apologize for the way I wrote the report originally.

**Comment by treeowl** [comment]
I should also mention that my employer has nothing to do with this bug
report.

**Comment by acowley** [comment]
Thank you; done and moving on. I will try to push a new version to hackage tonight, and see about a short blog post to demonstrate library usage to see if any other potential users have feedback on what would be useful as an API.

**Comment by thoughtpolice** [comment]
> Okay, I see this is a @well-typed bug report. Look, another program whose usability as a library is notoriously bad is GHC. Now imagine the rant your colleague @thoughtpolice would post on Reddit if somebody opened a GHC bug whose entirety was

Anthony, we're friends, but for the *love of god*: do not use me, or my employer(s), or anything of the sort as a cudgel in some random arguments on a bug tracker -- especially when you do not even know if what you are saying makes sense (because, I can assure you, for reasons you are not aware of: they don't make much sense). Thanks.

Aside from me deciding to read my GH notifications today to possibly respond to things (which, after a long time, I have *carefully* cultivated to make useful again), and in turn pissing me off a whole fucking lot -- you getting into random shitfits isn't my problem, and I don't give a shit. So don't bring me into it; just talk behind everyone's back like everyone else in the Haskell community already fucking does, thanks.

**Comment by acowley** [comment]
Sorry, @thoughtpolice.

**Comment by thoughtpolice** [comment]
I honestly appreciate the apology. Sorry for being such a stupid hothead. These days I do not work on GHC much anymore, or really at all; my health (of all sorts) is better off for it, and I'm happier and more free. A byproduct of this is that my views on the nature of labor, and people writing software, have changed significantly, and affected my outward perception.

You might now better understand why your hypothetical was irritating, I hope.

But I will tell you this: if *you* are irritated by low quality bug reports being submitted to your project? I understand that is time consuming and irritating. You have to draw the line between helping the issue at hand -- and also thinking about how to foster a scenario, a project, where you can have less of it. Balance in everything.

In fact, I would suggest you talk to someone about it, because it is very tiresome to have to do repeatedly, and I would not wish it on anyone without some form of support to lean on (emotional, verbal, whatever). And I think talking about it, truthfully -- as a structural issue surrounding free software -- is very important, and will teach us tactics for better managing these things. We should do it more often.

Perhaps you could talk with someone who did it everyday for 3 years as a full time job, or something.

**Comment by acowley** [comment]
When this was random internet person being a jerk, I said it was unhelpful and closed it. When I eventually found that David must be familiar with you and how outspoken you’ve been about this kind of stuff, I responded at greater length.

I guess I disagree with you on this: I think people who should know better should be called out when they screw up. Just like you called me out for the ill-considered at-mentions.

Further, I do not apologize for linking Neil’s tweet because I always find it hilarious.

**Comment by thoughtpolice** [comment]
> I think people who should know better should be called out when they screw up. Just like you called me out for the ill-considered at-mentions.

That's fine, and I don't care if you do so. Why would I? It's not my turf. What isn't fine, and what I do care about, is using me as a cudgel in your argument when you barely know or understand my situation, it would seem. That isn't your fault, because I don't go around just telling people. On the other hand, you can just not do it. Why? Because you can make that argument on your own. And also, because...

> Further, I do not apologize for linking Neil’s tweet because I always find it hilarious.

That is *not* what I was referring to, nor do I even disagree with the tweet. How you can see that tweet as what I was referring to when I said "talking behind peoples backs" shows how -- quite clearly -- you tell *yourself* a lot of narratives about what people think, without actually fucking asking them. (Especially considering, you know, I *follow* Neil, and he wasn't addressing me. Kind of hard to spin that as "behind my back", really.)

I was speaking about a general tendancy in the Haskell community that has shown itself over time. And frankly, rather than summoning me with a public argument and putting me out as some fucking tool, I'd much rather you just go do it half-assed way behind someone's back, in some lame back alley (it'll save us all the grief of me having to fucking whine at you, in public -- and you enjoy doing so with other people who actually care about such nonsense).

In fact, in this *particular* case, I believe I've made the argument about 5,000,000 times, in numerous places, that the GHC API is bad, and a "consumer focused" API would be a good addition to the project. If you haven't seen that, that isn't my problem. Nor are whatever weird narratives you spin.

So not only is your attempt to use me as a rhetorical device in this case, quite literally, *flat out fucking wrong* because I agree with you, in that instance[1], it is also bad because you apparently see the need to summon me and then invent narratives surrounding my motivations.

Again, do not use me in your lame arguments on your own bug reports. I have my own pathetic arguments to engage in, after all, and whatever lies you tell yourself about the nature of my arguments are just that: lies, that you told yourself. And only you can do something about them.

**Comment by acowley** [comment]
You’re reading much more into everything I’ve written than I ever intended, which makes your point. I don’t know what narrative I’m in from your point of view, but it’s clearly an awful one, so I will retreat to my original apology for mentioning you without further jokes or anything else. 

I truly and honestly have no idea what behind the back things you’re referring to or whatever lies or otherwise are involved in anything mentioned. I honestly thought that the levity in Neil’s tweet was understood. You can have a last word if you’d like; I’ve clearly walked into something and I don’t think there’s anything I could say to repair that.
